# Base Prompt Template Configuration
# This defines the core structure of the mental health prediction prompt

metadata:
  name: "Mental Health Prediction - Base"
  version: "1.0"
  description: "Standard prompt template for anxiety and depression prediction from sensor data"
  author: "KAIST ICLab - Gyuna Kim"

# Prompt structure
structure:
  title: "# Mental Health Prediction Task\n"
  sections:
    - name: role
      header: "## Role"
    - name: task
      header: "## Task"
    - name: context
      header: "## Context"

# Role definition
role:
  description: |
    You are an expert clinical psychologist and data scientist specializing in 
    mental health assessment using digital phenotyping data. You have extensive 
    experience in interpreting behavioral patterns from smartphone and wearable 
    device sensors.

# Task definition
task:
  objective: |
    Your task is to predict mental health risk levels (specifically anxiety and 
    depression) based on sensor-derived behavioral features collected from 
    smartphones and wearable devices over a 7-day period.
  
  targets_header: "**Prediction Targets:**"
  output_targets:
    - name: "Anxiety"
      classes: ["Low Risk", "High Risk"]
      threshold: "PHQ-4 anxiety score >= 2"
    - name: "Depression"
      classes: ["Low Risk", "High Risk"]
      threshold: "PHQ-4 depression score >= 2"

# Context definition
context:
  background: |
    Research has shown that behavioral patterns captured through smartphone and 
    wearable sensors can serve as digital biomarkers for mental health conditions.
  
  clinical_header: "**Clinical Associations:**"
  clinical_associations:
    depression:
      title: "Depression Indicators"
      patterns:
        - indicator: "Reduced physical activity and movement"
          evidence: "Lower step counts, less distance traveled"
        - indicator: "Decreased social interactions"
          evidence: "Fewer calls, less Bluetooth contacts"
        - indicator: "Irregular sleep patterns or excessive sleep"
          evidence: "Changed sleep duration, efficiency"
        - indicator: "Less time spent outside home"
          evidence: "Higher time at home, lower location entropy"
        - indicator: "Reduced digital engagement"
          evidence: "Fewer screen unlocks, less app usage"
    
    anxiety:
      title: "Anxiety Indicators"
      patterns:
        - indicator: "Irregular movement patterns"
          evidence: "High location entropy, erratic mobility"
        - indicator: "Disrupted sleep"
          evidence: "More awake time during sleep, lower efficiency"
        - indicator: "Increased or erratic phone usage"
          evidence: "Irregular screen time patterns"
        - indicator: "Changes in social communication"
          evidence: "Altered call/message patterns"
  
  features_header: "**Feature Categories:**"
  feature_categories:
    - name: "Sleep"
      prefix: "f_slp"
      description: "Sleep duration, efficiency, bedtime, wake time"
    - name: "Calls"
      prefix: "f_call"
      description: "Incoming/outgoing call counts, duration, contacts"
    - name: "Bluetooth"
      prefix: "f_blue"
      description: "Unique devices detected (proxy for social proximity)"
    - name: "Screen"
      prefix: "f_screen"
      description: "Unlock count, duration (digital engagement)"
    - name: "Steps"
      prefix: "f_steps"
      description: "Step counts, activity bouts (physical activity)"
    - name: "Location"
      prefix: "f_loc"
      description: "Distance, home time, entropy (mobility patterns)"

# Important notes
notes_header: "**Important Notes:**"
notes:
  - "Features are normalized to [-1, 1] range within each individual"
  - "Positive values indicate above-average for that person"
  - "Negative values indicate below-average for that person"
  - "Consider both absolute values and relative changes"
  - "Missing values (NaN) indicate insufficient data for that feature"

