# Base Prompt Template Configuration
# This defines the core structure of the mental health prediction prompt

metadata:
  name: "Mental Health Prediction - Base"
  version: "1.0"
  description: "Standard prompt template for anxiety and depression prediction from sensor data"
  author: "KAIST ICLab"

# Prompt structure
structure:
  title: "# Mental Health Prediction Task\n"
  sections:
    - name: role
      header: "## Role"
    - name: task
      header: "## Task"
    - name: context
      header: "## Context"

# Role definition
role:
  description: |
    You are an expert clinical psychologist and data scientist specializing in mental health assessment using digital phenotyping data.

# Task definition
task:
  objective: |
    Predict mental health risk levels (anxiety and depression) from smartphone and wearable sensor-derived behavioral features.
  
  # CES-specific task objective
  objective_ces: |
    Predict mental health risk levels (anxiety, depression, and stress) from smartphone sensor-derived behavioral features collected from college students.
  
  targets_header: "**Prediction Targets:**"
  output_targets:
    - name: "Anxiety"
      classes: ["Low Risk", "High Risk"]
      threshold: "PHQ-4 anxiety score > 2"
    - name: "Depression"
      classes: ["Low Risk", "High Risk"]
      threshold: "PHQ-4 depression score > 2"
  
  # CES-specific targets (includes stress)
  output_targets_ces:
    - name: "Anxiety"
      classes: ["Low Risk", "High Risk"]
      threshold: "PHQ-4 anxiety score > 2"
    - name: "Depression"
      classes: ["Low Risk", "High Risk"]
      threshold: "PHQ-4 depression score > 2"
    - name: "Stress"
      classes: ["Low Risk", "High Risk"]
      threshold: "Stress score > 2"

# Context definition
context:
  background: |
    Behavioral patterns from smartphones and wearables can serve as digital biomarkers for mental health conditions. Use the following symptom–feature mappings as soft guidelines, not absolute rules, since sensor data may be noisy or incomplete.
  
  # CES-specific background (includes college student context)
  background_ces: |
    The data is from college students. Academic schedule and social life may affect their behavior patterns, 
    but avoid assuming specific causes without supporting evidence.

    Note that depression and anxiety are typically assessed over the past two weeks, reflecting longer-term affective trends, whereas stress levels often represent current or recent states.
    Use the following symptom–feature mappings as soft guidelines, not absolute rules, since sensor data may be noisy or incomplete.
  
  clinical_header: "**Clinical Associations:**"
  clinical_associations:
    depression:
      title: "Depression Indicators"
      patterns:
        - indicator: "Anhedonia"
          features: "Call count, Total distance, Number of places visited"
          patterns: "Decreased social interactions and reduced movement"
        - indicator: "Insomnia or hypersomnia"
          features: "Sleep duration, Sleep efficiency, Duration in bed"
          patterns: "Irregular sleep pattern or excessive sleep"
        - indicator: "Psychomotor agitation or retardation"
          features: "Daily step count, Total distance, Time at home"
          patterns: "Reduced activity (retardation) or restless increase in activity (agitation)"
        - indicator: "Fatigue or loss of energy"
          features: "Daily step count"
          patterns: "Persistent decrease in daily steps from baseline"
        - indicator: "Diminished ability to think or concentrate"
          features: "Screen unlock duration, App session duration, App switching"
          patterns: "Shortened sustained attention (frequent, short)"
    
    anxiety:
      title: "Anxiety Indicators"
      patterns:
        - indicator: "Restlessness or feeling keyed up / on edge"
          features: "Daily step count"
          patterns: "Frequent movement"
        - indicator: "Easily fatigued"
          features: "Daily step count"
          patterns: "Decreased daily activity and rapid decline in energy"
        - indicator: "Difficulty concentrating"
          features: "Screen unlock duration, App session duration, App switching"
          patterns: "Shortened sustained attention, fragmented focus"
        - indicator: "Sleep disturbance"
          features: "Sleep duration, Sleep efficiency, Duration in bed"
          patterns: "Difficulty initiating or maintaining sleep, fragmented sleep patterns"
    
    stress:
      title: "Stress Indicators"
      patterns:
        - indicator: "Physiological arousal"
          features: "Movement patterns, Sleep quality"
          patterns: "Heightened restlessness, erratic activity, reduced sleep quality"
        - indicator: "Avoidance and withdrawal behaviors"
          features: "Time at home, Social interactions, Daily activity levels"
          patterns: "Reduced mobility, limited social engagement, and withdrawal from usual routines reflecting coping or exhaustion"
        - indicator: "Cognitive overload"
          features: "Screen usage patterns, App session duration, App switching"
          patterns: "Distracted attention, increased phone checking, difficulty focusing"
        - indicator: "Disrupted daily rhythm"
          features: "Sleep timing, Activity timing, Location transitions"
          patterns: "Irregular schedules, inconsistent activity timing, and unstable routine patterns"
  
# Important notes
notes_header: "**Notes:**"
notes:
  - "Treat missing values (NaN) as non-evidence and acknowledge limitations due to missingness."
